#!/usr/bin/env bash
# Recolor only Susnix-owned artifacts. No background polling or new dependencies.
set -euo pipefail
[[ $# -eq 18 ]] || { echo 'Expected the 18 semantic theme colors.' >&2; exit 2; }
for desktop_color in "$@"; do
    [[ "$desktop_color" =~ ^#[[:xdigit:]]{6}$ ]] || { echo 'Invalid theme color.' >&2; exit 2; }
done
desktop_background="${1#\#}"; desktop_surface="${3#\#}"
desktop_primary="${5#\#}"; desktop_secondary="${6#\#}"
desktop_accent="${7#\#}"; desktop_text="${8#\#}"
desktop_muted="${9#\#}"; desktop_border="${10#\#}"
desktop_success="${11#\#}"; desktop_warning="${12#\#}"; desktop_danger="${13#\#}"
desktop_config="${XDG_CONFIG_HOME:-$HOME/.config}/susnix"
mkdir -p "$desktop_config"
desktop_temp="$(mktemp "$desktop_config/.foot-colors.XXXXXX")"
trap 'rm -f -- "$desktop_temp"' EXIT
cat > "$desktop_temp" <<INI
# Generated by Susnix from colors.json; edit the global palette instead.
[main]
font=monospace:size=11
pad=14x12

[colors-dark]
alpha=0.94
background=$desktop_background
foreground=$desktop_text
regular0=$desktop_surface
regular1=$desktop_danger
regular2=$desktop_success
regular3=$desktop_warning
regular4=$desktop_primary
regular5=$desktop_secondary
regular6=$desktop_accent
regular7=$desktop_muted
bright0=$desktop_border
bright1=$desktop_danger
bright2=$desktop_success
bright3=$desktop_warning
bright4=$desktop_primary
bright5=$desktop_secondary
bright6=$desktop_accent
bright7=$desktop_text
selection-background=$desktop_secondary
selection-foreground=$desktop_text
INI
mv "$desktop_temp" "$desktop_config/foot.ini"
# Lua configs require eval rather than the legacy keyword API.
if [[ -n "${HYPRLAND_INSTANCE_SIGNATURE:-}" ]] && command -v hyprctl >/dev/null; then
    hyprctl eval "hl.config({general={col={active_border={colors={\"rgba(${desktop_primary}ee)\",\"rgba(${desktop_secondary}dd)\"},angle=45},inactive_border=\"rgba(${desktop_border}88)\"}},decoration={shadow={color=0xff${desktop_background}}}})" >/dev/null
fi
